- id: clean-diagrams
  name: clean unused diagrams
  description: This hook cleans unused diagrams
  entry: vitepress-plugin-diagrams clean --delete
  files: ^docs/
  types: [svg, markdown]
  pass_filenames: false
  language: node
- id: check-missing-diagrams
  name: check missing diagrams
  description: This hook checks if diagrams are missing from the docs
  entry: vitepress-plugin-diagrams check-missing
  files: ^docs/
  types: [svg, markdown]
  pass_filenames: false
  language: node
